# Site settings
title: Found & Made Recipes
email: me@jeffreylarrimore.com
description: 'A collection of vegan recipes found & created. Trying to see how the Markdown and recipes will work in Github.
Original idea from [@MattKosoy](https://github.com/MattKosoy).
Maybe Eventually hooking up a [Jekyll](http://jekyllrb.com)
backend to this so we can have a live site and git repo in the background.'
baseurl: "/vegan-recipes" # the subpath of your site, e.g. /blog/
url: "http://jeffreylarrimore.com" # the base hostname & protocol for your site
twitter_username: okayjeffrey
github_username:  okayjeffrey

# Build settings
markdown: kramdown
